### ISSUE TITLE
using a scene for entity_on does not work

### ISSUE THREAD

**Issue by mikepell007** [danobot/appdaemon-motion-lights#1]
If you specify a scene for entity_on, the state is always "scening" which results in:

... INFO xxx Motion Lights: Motion Sensor binary_sensor.xxx_motion triggered
... INFO xxx Motion Lights: Current state of scene.xxx_on_dim is scening
... INFO xxx Motion Lights: Entity is already switched on. Motion trigger ignored.

because  if entityState == "off":  will never be true for a scene.

Perhaps:

if entityState != "on", although I don't know what other affects that may have.

**Comment by danobot** [comment]
Thank for that, feel free to PR a fix. I don't use scenes myself and didn't realise they have a different state :)
Can you post your configuration please?

**Comment by danobot** [comment]
For the component to work `entity_on` must have `on` and `off` states. Scenes are always in `scening` state regardless of whether they are active or not. As such the component does not support scenes and scripts for the moment. The addition of `entity_off` was supposed to fix this.

The only way I can think of right now to make it work would be to separate the `entity_on` into `entity_on` and `entity_state` where `entity_state` is the entity whose state should be used to control the motion light.

I am working on a fix for this :)

**Comment by danobot** [comment]
I knew there was a way to do this already... This is not documented well. You can actually specify an `entity` to be used for entity state and use `scene`/`script` for `entity_on`.  You must also supply `entity_off` to undo what `entity_on` turned on.

```yaml
defect_test:
  module: motion_lights
  class: MotionLights
  entity: light.tv_led
  entity_on: scene.presence_lights
  entity_off: script.turn_off_presence_lights
  sensors:
    - binary_sensor.living_room_motion
```

This will activate your scene, observe an entity who is part of the scene, and use the `entity_off` script to turn off the scene when it times out. 
I will update the documentation.
